spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/vitamin"
    username: "vitamin"
    password: "vitamin"
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        generate_statistics: true